### ISSUE TITLE
Code 502

### ISSUE THREAD

**Issue by im-dim** [SumoLogic/logstash-output-sumologic#66] opened 2021-09-10 12:22 UTC
The previous issue was closed with response about code 428 but we are receiving 502...

We are getting a lot of intermittent **502** errors like below but some data IS coming to Sumo.
Is there a limit on ingest requests per minute or something?
How can we be sure that we get all data?

[2021-09-02T10:57:57,724][ERROR][logstash.outputs.sumologic][sumo_out] request rejected {:token=>26, :code=>502, :headers=>{"X-Sumo-Client"=>"logstash-output-sumologic", "X-Sumo-Category"=>"elastiflow", "X-Sumo-Host"=>"ct-centos001", "X-Sumo-Name"=>"elastiflow", "Content-Type"=>"text/plain"}, :contet=>"{"event":{"type":"net"}

**Comment by astencel-sumo** [comment] 2021-09-10 12:56
Duplicate of #66, nothing to add here.

**Closed by astencel-sumo** 2021-09-10 12:56 UTC
